### PR TITLE
Add polish translation

### PR DESCRIPTION
**Pull request by Antoni-Czaplicki**

### CODE REVIEW

**Comment by IATkachenko** [comment]
Thank you!

**Comment by IATkachenko** [comment]
@Antoni-Czaplicki, would you like to add state translation before next release? 
Check https://github.com/IATkachenko/HA-SleepAsAndroid/commit/12d649c779604491574bb7d237a4222aa7927aea for details (changes `sensor.py` made to allow state translation support).

**Comment by Antoni-Czaplicki** [comment]
Sure, but does it change the names of states in automations?

**Comment by IATkachenko** [comment]
No, states will stay as json keys, like before:
изображение
It will affect only to state in UI
изображение

**Comment by Antoni-Czaplicki** [comment]
Done in #36

**Pull request merged**
