### PR TITLE
fix: for breaking change in 2024.12.0

### LINKED ISSUE #74: Fails to start on HA version 2024.12b3
### Home Assistant
**Version:**
**Installation method** (according to [instructions](https://www.home-assistant.io/installation/)):
[ ] Operating System

### Integration

**Installation method:**
[ ] HACS

**Integration version:** 
2.3.0
### Application settings

**topic:**
[ ] I can see MQTT messages from application at MQTT-server
## Steps to reproduce
Was working under HA version 2024.12b2 but after updating to beta 3 it fails to startup
## Debug log
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: December 2, 2024 at 17:13:27 (1 occurrences)
Last logged: December 2, 2024 at 17:13:27

Error while setting up sleep_as_android platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sleep_as_android/sensor.py", line 50, in async_setup_entry
    await instance.subscribe_root_topic(async_add_entities)
  File "/config/custom_components/sleep_as_android/__init__.py", line 292, in subscribe_root_topic
    self._subscription_state = await subscribe_2022_03(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/sleep_as_android/__init__.py", line 262, in subscribe_2022_03
    result = subscription.async_prepare_subscribe_topics(
        hass=_hass,
        new_state=_state,
        topics=_topic,
    )
TypeError: async_prepare_subscribe_topics() got an unexpected keyword argument 'new_state'. Did you mean 'sub_state'?
```

### PR DESCRIPTION
**Pull request by tnt944445**
To resolve #74 

Seems like "new_state" isn't working anymore for updating sensor states. I've replaced all instanaces of "new_state" with "sub_state" and done some minimal testing with my automations and they seem to be working.

Can't find any documentation from HA about the change, unsure if "new_state" was deprecated.

Merging this as it sits may break in older version of HA. I don't have another instance to test on at the moment.

PS. This isn't my forte, I just really like this integration.

### CODE REVIEW

**Comment by tofurky** [comment]
Looks like it was this, not flagged as a breaking change: https://github.com/home-assistant/core/pull/130866

**Comment by tnt944445** [comment]
I know this integration was important to me to continue working. I assume I'm not the only. In the meantime you can add my fork as a custom repository in HACS to get it working again.

https://github.com/tnt944445/HA-SleepAsAndroid

**Comment by SCBionicle** [comment]
Question: would this be merged? Or should I install this fork temporarily?

**Comment by tnt944445** [comment]
> Question: would this be merged? Or should I install this fork temporarily? 

I would hope it gets merged. The maintainer looks like he's been inactive for a bit though. Up to you if you want to install the fork. I'll keep maintaining it if this repo is dead.

**Comment by retikulumx** [comment]
Guys, just fix it yourself.
Open the `__init__.py` in `/config/custom_components/sleep_as_android/` , find `new_state`, change it to `sub_state` (two times), save the file and restart HA.

**Comment by tnt944445** [comment]
> Guys, just fix it yourself. Open the `__init__.py` in `/config/custom_components/sleep_as_android/` , find `new_state`, change it to `sub_state` (two times), save the file and restart HA.

It's a very simple fix, but I don't expect everyone using HA to be able to just go edit python files like that.

**Pull request closed without merging**
